FROM taojintianxia/alpine-jdk8

MAINTAINER Nianjun Sun "kane.sun@outlook.com"

COPY springboot-hello-world-0.0.1-SNAPSHOT.jar /opt/springboot-hello-world.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/opt/springboot-hello-world.jar"]